name: scope_app
description: "App para Trade Marketting de Scope Group"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.1+4

environment:
  sdk: ">=3.2.0-40.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase – ramas compatibles entre sí
  firebase_core: ">=3.4.1 <4.0.0"
  firebase_auth: ">=5.1.0 <6.0.0"
  cloud_firestore: ">=5.0.0 <6.0.0"
  firebase_storage: ">=12.0.0 <13.0.0"
  firebase_messaging: ">=15.0.0 <16.0.0"

  # Otros
  intl:
  fluttertoast: ^8.2.12
  geolocator:
  geocoding:
  animated_splash_screen:
  url_launcher:
  camera:
  image_picker:
  path_provider:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  app_settings: ^5.1.1

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
